version: "3.3"
services:
 database:
  image: mariadb
  ports:
   - "3307:3307"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: likelion
   MYSQL_USER: likelion
   MYSQL_PASSWORD: likelion11